# Generated by Django 3.2.6 on 2021-08-11 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chinook', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='albums',
            options={},
        ),
        migrations.AlterModelOptions(
            name='artists',
            options={},
        ),
        migrations.AlterModelOptions(
            name='customers',
            options={},
        ),
        migrations.AlterModelOptions(
            name='employees',
            options={},
        ),
        migrations.AlterModelOptions(
            name='genres',
            options={},
        ),
        migrations.AlterModelOptions(
            name='invoiceitems',
            options={},
        ),
        migrations.AlterModelOptions(
            name='invoices',
            options={},
        ),
        migrations.AlterModelOptions(
            name='mediatypes',
            options={},
        ),
        migrations.AlterModelOptions(
            name='playlists',
            options={},
        ),
        migrations.AlterModelOptions(
            name='playlisttrack',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sqlitestat1',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tracks',
            options={},
        ),
    ]
