# Generated by Django 3.2.6 on 2021-08-12 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chinook', '0002_auto_20210811_2214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='albums',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='artists',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='customers',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='employees',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='genres',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='invoiceitems',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='invoices',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='mediatypes',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='playlists',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='playlisttrack',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='sqlitestat1',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tracks',
            options={'managed': False},
        ),
    ]
