# Generated by Django 3.2.6 on 2021-08-12 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chinook', '0003_auto_20210812_1031'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='invoiceitems',
            table='invoiceitems',
        ),
        migrations.AlterModelTable(
            name='mediatypes',
            table='mediatypes',
        ),
        migrations.AlterModelTable(
            name='playlisttrack',
            table='playlisttrack',
        ),
        migrations.AlterModelTable(
            name='sqlitestat1',
            table='sqlitestat1',
        ),
    ]
